(function () {
  var PS = window.PS = window.PS || {};
  PS.videos = [
    {"id": "race_office2", "file": "supplementary/videos/race_office2.mp4", "poster": "supplementary/videos/race_office2.jpg", "label": "Replica office2 · real time", "caption": "MASt3R-SLAM and Pow3R-SLAM on the same input frames of Replica office2, with the sensor depth given only to Pow3R-SLAM, replayed at ×1.0 (real time). The wall clock starts at the first frame and excludes model loading. The only filtering on either map is that system's own confidence gate, here the top 88 %.", "seconds": 73.21, "bytes": 7641361, "group": "Real-time comparisons"},
    {"id": "race_redkitchen", "file": "supplementary/videos/race_redkitchen.mp4", "poster": "supplementary/videos/race_redkitchen.jpg", "label": "7-Scenes redkitchen · real time", "caption": "MASt3R-SLAM and Pow3R-SLAM on the same input frames of 7-Scenes redkitchen, with the sensor depth given only to Pow3R-SLAM, replayed at ×1.0 (real time). The wall clock starts at the first frame and excludes model loading. The only filtering on either map is that system's own confidence gate, here the top 80 %.", "seconds": 40.21, "bytes": 7631375, "group": "Real-time comparisons"},
    {"id": "race_mannequin_5", "file": "supplementary/videos/race_mannequin_5.mp4", "poster": "supplementary/videos/race_mannequin_5.jpg", "label": "ETH3D-SLAM mannequin_5 · real time", "caption": "MASt3R-SLAM and Pow3R-SLAM on the same input frames of ETH3D-SLAM mannequin_5, with the sensor depth given only to Pow3R-SLAM, replayed at ×1.0 (real time). The wall clock starts at the first frame and excludes model loading. The only filtering on either map is that system's own confidence gate, here the top 70 %.", "seconds": 69.54, "bytes": 7706103, "group": "Real-time comparisons"},
    {"id": "race_replay", "file": "supplementary/videos/race_replay.mp4", "poster": "supplementary/videos/race_replay.jpg", "label": "Replica office2 · MASt3R-SLAM vs. Pow3R-SLAM", "caption": "Both systems on the same frames of Replica office2 against one shared wall clock, replayed at ×4.0. Sensor depth goes only to Pow3R-SLAM. Both maps at the top 88 % of their own confidences, ground truth dashed.", "seconds": 21.96, "bytes": 3830412, "group": "From the video"},
    {"id": "map_comparison", "file": "supplementary/videos/map_comparison.mp4", "poster": "supplementary/videos/map_comparison.jpg", "label": "Replica office3 · map quality", "caption": "The two finished maps on one shared camera path through Replica office3, each at the top 88 % of its own confidences (no filtering): Chamfer 5.45 cm for MASt3R-SLAM against 2.46 cm for Pow3R-SLAM.", "seconds": 17.0, "bytes": 3781734, "group": "From the video"},
    {"id": "unscaled", "file": "supplementary/videos/unscaled.mp4", "poster": "supplementary/videos/unscaled.jpg", "label": "ETH3D-SLAM mannequin_5 · metric scale", "caption": "Trajectories aligned to ground truth by rotation and translation only, with no rescaling. The monocular map has to be stretched by 1.34× to match the room, Pow3R-SLAM's by 1.01×. A one-meter rod lies in both maps. Both maps at the top 70 % of their confidences.", "seconds": 17.0, "bytes": 3339963, "group": "From the video"},
    {"id": "ablation", "file": "supplementary/videos/ablation.mp4", "poster": "supplementary/videos/ablation.jpg", "label": "TUM fr1/room · depth-prior ablations", "caption": "Three runs of TUM fr1/room from above with the ceiling cut away. No depth prior, depth conditioning only, and all three depth sites. Each map at the top 70 % of its own confidence.", "seconds": 19.96, "bytes": 3854571, "group": "From the video"},
    {"id": "hybrid", "file": "supplementary/videos/hybrid.mp4", "poster": "supplementary/videos/hybrid.jpg", "label": "7-Scenes redkitchen · hybrid ICP variant", "caption": "The default against the optional hybrid, which alternates network calls with ICP over the sensor depth, with a running count of ICP-tracked frames. Replayed at ×2.7, both maps at the top 80 % of their own confidences.", "seconds": 13.96, "bytes": 3812988, "group": "From the video"},
    {"id": "stairs", "file": "supplementary/videos/stairs.mp4", "poster": "supplementary/videos/stairs.jpg", "label": "7-Scenes stairs · where Pow3R-SLAM loses", "caption": "The repeated treads of 7-Scenes stairs, seen low and from the side. MASt3R-SLAM is ahead here (ATE 0.016 m against 0.044 m). Both maps at the top 65 % of their own confidences.", "seconds": 14.5, "bytes": 2491194, "group": "From the video"},
    {"id": "summary", "file": "supplementary/videos/summary.mp4", "poster": "supplementary/videos/summary.jpg", "label": "Four sequences building at once", "caption": "One sequence per dataset replayed together: TUM fr1/room, 7-Scenes redkitchen, Replica office3 and ETH3D-SLAM mannequin_5. Each map at its own gate: the top 70 %, 80 %, 88 % and 70 % of its own confidences.", "seconds": 12.0, "bytes": 3875157, "group": "From the video"}
  ];
})();
